name: Checking Code/Models 🔎

on:
  workflow_call:
    inputs:
      directory:
        description: The dependant directory to scan.
        required: false
        type: string
        default: database

jobs:

  validation:
    runs-on: ubuntu-latest
    name: 'Files type checking'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get code changes
        id: directory_code_modified
        uses: Ana06/get-changed-files@v2.1.0
        with:
          filter: |
            ${{ inputs.directory }}/*
            ${{ inputs.directory }}/*/*
      - name: Get Code changes
        id: other_code_modified
        uses: Ana06/get-changed-files@v2.1.0
        with:
          filter: |
            *
            !${{ inputs.directory }}/*
            !${{ inputs.directory }}/*/*
      - name: Fail if mix changes
        if: ${{ (join(steps.directory_code_modified.outputs.all, ',') != '' && join(steps.other_code_modified.outputs.all, ',') != '') }}
        run: |
          echo "::error ::Mixed code changes that is not allowed! It could be database and/or command changes that happened with other code changes."
          exit 1
